//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int ID { get; set; }
        public int DeptID { get; set; }
        public string UserName { get; set; }
        public int TimeSlot { get; set; }
        public int PhnNo { get; set; }
        public string Email { get; set; }
        public System.DateTime DOB { get; set; }
        public int Salary { get; set; }
        public string Address { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
