//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Status { get; set; }
        public int PhnNo { get; set; }
        public string Mail { get; set; }
        public System.DateTime DOB { get; set; }
        public int Salary { get; set; }
        public string Address { get; set; }
    }
}
