//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string PatientName { get; set; }
        public string Drugs { get; set; }
        public string LabResult { get; set; }
        public Nullable<int> PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
